#Most of my work lives at the intersection of offensive security, automation, and infrastructure — from Go APIs and WebSocket backends to C2 tooling and network utilities. I focus on clean architecture, realistic tradecraft, and practical tooling that people actually use.
#If my projects save you time, teach you something, or make your workflow better, consider buying a coffee to support continued development.
#https://buymeacoffee.com/icewzl
github: ice-wzl
buy_me_a_coffee: icewzl
